tags = [
    ["DP", "https://solved.ac/problems/tags/dp", "https://solved.ac/problems/tags/lis",
     "https://solved.ac/problems/tags/tsp"],
    ["구현", "https://solved.ac/problems/tags/implementation", "https://solved.ac/problems/tags/simulation"],
    ["그리디", "https://solved.ac/problems/tags/greedy"],
    ["완전탐색", "https://solved.ac/problems/tags/bruteforcing"],
    ["문자열", "https://solved.ac/problems/tags/string", "https://solved.ac/problems/tags/parsing",
     "https://solved.ac/problems/tags/kmp"],
    ["백트래킹", "https://solved.ac/problems/tags/backtracking"],
    ["그래프 탐색", "https://solved.ac/problems/tags/graphs", "https://solved.ac/problems/tags/graph_traversal",
     "https://solved.ac/problems/tags/dfs", "https://solved.ac/problems/tags/bfs"],
    ["투 포인터", "https://solved.ac/problems/tags/two_pointer", "https://solved.ac/problems/tags/sliding_window"],
    ["트리", "https://solved.ac/problems/tags/trees"],
    ["우선순위 큐", "https://solved.ac/problems/tags/proiroty_queue"],
    ["자료구조", "https://solved.ac/problems/tags/data_structures"],
    ["최단거리", "https://solved.ac/problems/tags/shortest_path", "https://solved.ac/problems/tags/dijkstra",
     "https://solved.ac/problems/tags/floyd_warshall", "https://solved.ac/problems/tags/bellman_ford"],
    ["누적합", "https://solved.ac/problems/tags/prefix_sum"],
    ["이진탐색", "https://solved.ac/problems/tags/binary_search", "https://solved.ac/problems/tags/ternary_search"],
    ["전처리", "https://solved.ac/problems/tags/precomputation"],
    ["수학", "https://solved.ac/problems/tags/math"],
    # 17 재귀 뒤로 추가
]
