tags = [
    ["DP", "https://solved.ac/problems/tags/dp", "https://solved.ac/problems/tags/lis",
     "https://solved.ac/problems/tags/tsp"],
    ["구현", "https://solved.ac/problems/tags/implementation", "https://solved.ac/problems/tags/simulation"],
    ["그리디", "https://solved.ac/problems/tags/greedy"],
    ["완전탐색", "https://solved.ac/problems/tags/bruteforcing"],
    ["문자열", "https://solved.ac/problems/tags/string", "https://solved.ac/problems/tags/parsing",
     "https://solved.ac/problems/tags/kmp", "https://solved.ac/problems/tags/trie"],
    ["백트래킹", "https://solved.ac/problems/tags/backtracking"],
    ["그래프 탐색", "https://solved.ac/problems/tags/graphs", "https://solved.ac/problems/tags/graph_traversal",
     "https://solved.ac/problems/tags/dfs", "https://solved.ac/problems/tags/bfs"],
    ["투 포인터", "https://solved.ac/problems/tags/two_pointer", "https://solved.ac/problems/tags/sliding_window"],
    ["트리", "https://solved.ac/problems/tags/trees"],
    ["우선순위 큐", "https://solved.ac/problems/tags/proiroty_queue"],
    ["자료구조", "https://solved.ac/problems/tags/data_structures"],
    ["최단거리", "https://solved.ac/problems/tags/shortest_path", "https://solved.ac/problems/tags/dijkstra",
     "https://solved.ac/problems/tags/floyd_warshall", "https://solved.ac/problems/tags/bellman_ford"],
    ["누적합", "https://solved.ac/problems/tags/prefix_sum"],
    ["이진탐색", "https://solved.ac/problems/tags/binary_search", "https://solved.ac/problems/tags/ternary_search"],
    ["전처리", "https://solved.ac/problems/tags/precomputation"],
    ["수학", "https://solved.ac/problems/tags/math"],
    ["재귀", "https://solved.ac/problems/tags/recursion"],
    ["분할정복", "https://solved.ac/problems/tags/divide_and_conquer"],
    ["정렬", "https://solved.ac/problems/tags/sorting"],
    ["위상정렬", "https://solved.ac/problems/tags/topological_sorting"],
    ["해싱", "https://solved.ac/problems/tags/hashing"],
    ["기하학", "https://solved.ac/problems/tags/geometry"],
    ["분리집합", "https://solved.ac/problems/tags/disjoint_set"],
    ["최소신장트리", "https://solved.ac/problems/tags/mst"],
    ["세그먼트트리", "https://solved.ac/problems/tags/segtree"],
    ["비트마스킹", "https://solved.ac/problems/tags/bitmask"],
    ["유량문제", "https://solved.ac/problems/tags/bipartite_matching", "https://solved.ac/problems/tags/flow"]
]

tiers = [
    [1, "Bronze V"], [1, "Sprout"],
    [2, "Bronze IV"],
    [3, "Bronze III"],
    [4, "Bronze II"],
    [5, "Bronze I"],
    [6, "Silver V"],
    [7, "Silver IV"],
    [8, "Silver III"],
    [9, "Silver II"],
    [10, "Silver I"],
    [11, "Gold V"],
    [12, "Gold IV"],
    [13, "Gold III"],
    [14, "Gold II"],
    [15, "Gold I"],
    [16, "Platinum V"],
    [17, "Platinum IV"],
    [18, "Platinum III"],
    [19, "Platinum II"],
    [20, "Platinum I"],
    [21, "Diamond V"],
    [22, "Diamond IV"],
    [23, "Diamond III"],
    [24, "Diamond II"],
    [25, "Diamond I"],
    [26, "Ruby V"],
    [27, "Ruby IV"],
    [28, "Ruby III"],
    [29, "Ruby II"],
    [30, "Ruby I"],
    [31, "Not ratable"], [31, "Unrated"]
]
